### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by zxt-triumph** [junyanz/BicycleGAN#20]
when I run command that bash ./scripts/train_edges2shoes.sh
I got following  error
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58
how to solve this problem?

**Comment by junyanz** [comment]
how big is your gpu memory? You may want to use smaller images and smaller models. ( `--loadSize 143 --fineSize 128 --which_model_netD basic_128_multi --which_model_netD2 basic_128_multi --which_model_netG unet_128 --which_model_netE resnet_128`)

**Comment by zxt-triumph** [comment]
Thank you for your reply.My gpu memory is only 3G.According to your suggestion, I modified the memory  but the problem is still not resolved.

**Comment by junyanz** [comment]
Could you give more details about your current problem?

**Comment by zxt-triumph** [comment]
batchSize: 2
beta1: 0.5
center_crop: False
checkpoints_dir: ../checkpoints_pub/edges2shoes/
conditional_D: False
continue_train: False
dataroot: ./datasets/edges2shoes
dataset_mode: aligned
disc_iters: 1
display_freq: 400
display_id: 1
display_port: 8097
display_winsize: 256
fineSize: 128
gan_mode: lsgan
gpu_ids: [0]
init_type: xavier
input_nc: 1
isTrain: True
lambda_GAN: 1.0
lambda_GAN2: 1.0
lambda_L1: 10.0
lambda_kl: 0.01
lambda_z: 0.5
loadSize: 143
lr: 0.0002
lr_decay_iters: 100
lr_policy: lambda
max_dataset_size: inf
model: bicycle_gan
nThreads: 4
name: edges2shoes_bicycle_gan
ndf: 64
nef: 64
ngf: 64
niter: 30
niter_decay: 30
nl: relu
no_flip: False
no_html: False
norm: instance
num_Ds: 2
nz: 8
output_nc: 3
phase: train
print_freq: 200
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 10000
serial_batches: False
update_html_freq: 4000
upsample: basic
use_dropout: True
use_same_D: False
where_add: all
which_direction: AtoB
which_epoch: latest
which_model_netD: basic_128_multi
which_model_netD2: basic_128_multi
which_model_netE: resnet_128
which_model_netG: unet_128
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
#training images = 49825
Loading model bicycle_gan...
---------- Networks initialized -------------
initialization method [xavier]
G_Unet_add_all(
  (model): UnetBlock_with_z(
    (down): Sequential(
      (0): Conv2d(9, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    )
    (submodule): UnetBlock_with_z(
      (down): Sequential(
        (0): LeakyReLU(0.2, inplace)
        (1): Conv2d(72, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
        (2): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
      )
      (submodule): UnetBlock_with_z(
        (down): Sequential(
          (0): LeakyReLU(0.2, inplace)
          (1): Conv2d(136, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
          (2): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False)
        )
        (submodule): UnetBlock_with_z(
          (down): Sequential(
            (0): LeakyReLU(0.2, inplace)
            (1): Conv2d(264, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
            (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
          )
          (submodule): UnetBlock_with_z(
            (down): Sequential(
              (0): LeakyReLU(0.2, inplace)
              (1): Conv2d(520, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
              (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
            )
            (submodule): UnetBlock_with_z(
              (down): Sequential(
                (0): LeakyReLU(0.2, inplace)
                (1): Conv2d(520, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
              )
              (submodule): UnetBlock_with_z(
                (down): Sequential(
                  (0): LeakyReLU(0.2, inplace)
                  (1): Conv2d(520, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                )
                (up): Sequential(
                  (0): ReLU(inplace)
                  (1): ConvTranspose2d(512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                  (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
                )
              )
              (up): Sequential(
                (0): ReLU(inplace)
                (1): ConvTranspose2d(1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
                (3): Dropout(p=0.5)
              )
            )
            (up): Sequential(
              (0): ReLU(inplace)
              (1): ConvTranspose2d(1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
              (2): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False)
              (3): Dropout(p=0.5)
            )
          )
          (up): Sequential(
            (0): ReLU(inplace)
            (1): ConvTranspose2d(1024, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
            (2): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False)
          )
        )
        (up): Sequential(
          (0): ReLU(inplace)
          (1): ConvTranspose2d(512, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
          (2): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
        )
      )
      (up): Sequential(
        (0): ReLU(inplace)
        (1): ConvTranspose2d(256, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
        (2): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False)
      )
    )
    (up): Sequential(
      (0): ReLU(inplace)
      (1): ConvTranspose2d(128, 3, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
      (2): Tanh()
    )
  )
)
Total number of parameters: 42143107
initialization method [xavier]
D_NLayersMulti(
  (model0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d(64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d(128, 256, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (6): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d(256, 1, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
  )
  (down): AvgPool2d(kernel_size=3, stride=2, padding=[1, 1], ceil_mode=False, count_include_pad=False)
  (model1): Sequential(
    (0): Conv2d(3, 32, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d(64, 128, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (6): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d(128, 1, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
  )
)
Total number of parameters: 830626
initialization method [xavier]
D_NLayersMulti(
  (model0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d(64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d(128, 256, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (6): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d(256, 1, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
  )
  (down): AvgPool2d(kernel_size=3, stride=2, padding=[1, 1], ceil_mode=False, count_include_pad=False)
  (model1): Sequential(
    (0): Conv2d(3, 32, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d(64, 128, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (6): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d(128, 1, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
  )
)
Total number of parameters: 830626
initialization method [xavier]
E_ResNet(
  (fc): Sequential(
    (0): Linear(in_features=256, out_features=8, bias=True)
  )
  (fcVar): Sequential(
    (0): Linear(in_features=256, out_features=8, bias=True)
  )
  (conv): Sequential(
    (0): Conv2d(3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): BasicBlock(
      (conv): Sequential(
        (0): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False)
        (1): LeakyReLU(0.2, inplace)
        (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False)
        (4): LeakyReLU(0.2, inplace)
        (5): Sequential(
          (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        )
      )
      (shortcut): Sequential(
        (0): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        (1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (2): BasicBlock(
      (conv): Sequential(
        (0): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
        (1): LeakyReLU(0.2, inplace)
        (2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False)
        (4): LeakyReLU(0.2, inplace)
        (5): Sequential(
          (0): Conv2d(128, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        )
      )
      (shortcut): Sequential(
        (0): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        (1): Conv2d(128, 192, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (3): BasicBlock(
      (conv): Sequential(
        (0): InstanceNorm2d(192, eps=1e-05, momentum=0.1, affine=False)
        (1): LeakyReLU(0.2, inplace)
        (2): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): InstanceNorm2d(192, eps=1e-05, momentum=0.1, affine=False)
        (4): LeakyReLU(0.2, inplace)
        (5): Sequential(
          (0): Conv2d(192, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        )
      )
      (shortcut): Sequential(
        (0): AvgPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=False, count_include_pad=True)
        (1): Conv2d(192, 256, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (4): LeakyReLU(0.2, inplace)
    (5): AvgPool2d(kernel_size=8, stride=8, padding=0, ceil_mode=False, count_include_pad=True)
  )
)
Total number of parameters: 1344080
-----------------------------------------------
model [BiCycleGANModel] was created
create web directory ../checkpoints_pub/edges2shoes/edges2shoes_bicycle_gan/web...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86dee07978>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86dee07978>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86dee07978>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 200, time: 0.094) , z_encoded_mag: 1.657, G_total: 6.010, G_L1_encoded: 3.340, z_L1: 0.914, KL: 0.201, G_GAN: 0.778, D_GAN: 0.956, G_GAN2: 0.776, D_GAN2: 1.027
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb24828>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24828>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24828>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb24ef0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 400, time: 0.098) , z_encoded_mag: 0.749, G_total: 4.592, G_L1_encoded: 2.822, z_L1: 0.419, KL: 0.047, G_GAN: 0.546, D_GAN: 1.173, G_GAN2: 0.758, D_GAN2: 0.750
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb325c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb325c0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb325c0>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 600, time: 0.099) , z_encoded_mag: 0.845, G_total: 3.890, G_L1_encoded: 2.083, z_L1: 0.418, KL: 0.044, G_GAN: 0.536, D_GAN: 1.061, G_GAN2: 0.809, D_GAN2: 0.877
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb24588>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24588>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24588>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb07dd8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb07dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb07dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 800, time: 0.098) , z_encoded_mag: 1.066, G_total: 4.022, G_L1_encoded: 2.441, z_L1: 0.319, KL: 0.075, G_GAN: 0.645, D_GAN: 0.893, G_GAN2: 0.541, D_GAN2: 1.060
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb2b588>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2b588>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2b588>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 1000, time: 0.094) , z_encoded_mag: 0.843, G_total: 3.546, G_L1_encoded: 2.086, z_L1: 0.391, KL: 0.042, G_GAN: 0.535, D_GAN: 1.145, G_GAN2: 0.492, D_GAN2: 1.022
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb2bd68>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 1, iters: 1200, time: 0.098) , z_encoded_mag: 0.643, G_total: 2.645, G_L1_encoded: 1.106, z_L1: 0.490, KL: 0.069, G_GAN: 0.517, D_GAN: 1.136, G_GAN2: 0.463, D_GAN2: 1.006
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/zxt/Downloads/123/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86deb24048>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24048>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxt/Downloads/123/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86deb24048>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by zxt-triumph** [comment]
zxt@zxt-ZHENGJIUZHE-REN7000:~$ python -m visdom.server
It's Alive!
INFO:tornado.access:200 POST /events (127.0.0.1) 9.74ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.33ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.36ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.34ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.34ms

**Comment by zxt-triumph** [comment]
Thank you so much.I have solved this problem with your help.
